### PR TITLE
Handle single quotes

### PR DESCRIPTION
**Pull request by chrisolesen**
Fix single quotes for record type json

### CODE REVIEW

**Comment by kennym** [comment]
LGTM.

Thank you for also bumping the version number! Will deploy a release later today.

**Comment by NicoP-S** [comment]
Hello,

I am struggeling with an textarea with linebreaks. These linebreaks does not get send via the API request (JSON).

Linebreaks are correcly escaped see:
 https://github.com/kennym/cf7-to-api/blob/master/includes/class-cf7-api-admin.php#L496-L498

But stripslashes which was added by this MR do remove all \n  resulting in a strage text...
`$json = $this->parse_json( stripslashes ( $lead ) );`

Can this change be reverted please?

**Comment by kennym** [comment]
@NicoP-S thanks for reporting this. I will revert this now

**Comment by kennym** [comment]
@NicoP-S change reverted in 1.4.8 - please let me know if you have any other issues.

**Comment by NicoP-S** [comment]
I just updated the plugin and now it works! Thanks :thumbsup:

**Pull request merged**
